/**
 * Phase 08 POC fixture — stock.naver.com community discussion JSON API
 *
 * Captured: 2026-04-18 via Bright Data Web Unlocker (zone=gh_radar_naver, country=kr)
 * Endpoint: GET https://stock.naver.com/api/community/discussion/posts/by-item
 *
 * Required query params (server-side zod validation):
 *   discussionType=domesticStock & itemCode={code}
 *   isHolderOnly=false & excludesItemNews=false & isItemNewsOnly=false
 *   isCleanbotPassedOnly=false & pageSize=50
 *
 * SoT for workers/discussion-sync parseDiscussionsJson.test.ts and
 * server/tests/routes/discussions.test.ts.
 *
 * Posts trimmed to 5 per stock to keep diff readable; full responses
 * (50 posts each) live in /tmp/poc-naver/zone-{code}-v2.json during POC.
 */

import type { NaverDiscussionApiResponse } from './naver-board-types';

export const NAVER_BOARD_JSON_SAMPLE_ACTIVE: NaverDiscussionApiResponse = {
  "offset": "-9223372036854775807",
  "pageSize": 50,
  "posts": [
    {
      "id": "417878625",
      "orderNo": "-417878625",
      "discussionType": "domesticStock",
      "itemCode": "005930",
      "itemName": "삼성전자",
      "postType": "normal",
      "writer": {
        "profileId": "29070681473228904",
        "profileType": "normal",
        "nickname": "서준사랑",
        "imageUrl": "https://ssl.pstatic.net/imgstock/fn/real/_front/image/profile/avatar-11.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T10:02:42",
      "title": "미련한 투자법",
      "contentSwReplaced": "상승시 목표치 도달하면 매도<br>오를땐 파는거 아니다<br>내릴때 파는거지 ㅎ",
      "contentSwReplacedButImg": "상승시 목표치 도달하면 매도 오를땐 파는거 아니다 내릴때 파는거지 ㅎ",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 61, \"st\": 97}, \"dis\": \"N\"}]}, \"id\": \"01KPF1P2XT95YYQ4DXXS5PJEGQ\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-9b16baad-5337-4924-890d-4a7ba1b2de2a\", \"value\": [{\"id\": \"SE-7bb715c8-e1cf-4f72-9af7-c49a378bca2b\", \"nodes\": [{\"id\": \"SE-4b81da07-139e-4f70-9b7b-dbba09f56b57\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"상승시 목표치 도달하면 매도\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-dc4de387-bb7d-439d-bf3c-cec8f54c0875\", \"nodes\": [{\"id\": \"SE-3d846492-f13d-445f-a000-caff67a43759\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-9fe7bcf8-408b-49a1-a99e-efad100e0497\", \"nodes\": [{\"id\": \"SE-a36e2a22-e14b-4ae9-9e78-163667a28dc6\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"오를땐 파는거 아니다\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-43633204-1c40-4a23-ab2a-376572b1956a\", \"nodes\": [{\"id\": \"SE-55f3fe90-db20-491d-b8a1-18ca505797ad\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-cb26c11c-74ed-4489-9e76-ced54c1ce337\", \"nodes\": [{\"id\": \"SE-31742cff-96dc-4d93-b434-75a5b9e312a7\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"내릴때 파는거지 ㅎ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417878611",
      "orderNo": "-417878611",
      "discussionType": "domesticStock",
      "itemCode": "005930",
      "itemName": "삼성전자",
      "postType": "normal",
      "writer": {
        "profileId": "28660330882492942",
        "profileType": "normal",
        "nickname": "똑똑한페퍼민트zz",
        "imageUrl": "https://sec-discuss-phinf.pstatic.net/MjAyNTA3MDRfMTE2/MDAxNzUxNjA2NDkxNDI5.PQbncAVCmiXgIDVAnIxDGkLiAyZ7yCKIjwyDkRpOkn4g.JLyA1Jk3_2-N2kSgDJM5JWmiDAw1Jro39Ebc9fShqIMg.JPEG/profile_20250704142131.jpg",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T10:01:29",
      "title": "★자주국방하자~~",
      "contentSwReplaced": "난 군대 갔다왔으니까 꼭하자~~<br>북한처럼 남자 10년 여자들 7년씩 군대 생활 하고 싶다는데 ~~<br>꼭해라~~<br>자주국방타령하니까 IRI에서 장동혁대표 초청한걸 가지고<br>무식한넘들이 놀러갔다고 선동하니까<br>그 선동질에 놀아나는꼴이라니 ㅋㅋㅋ<br>자주국방해서 주식 반토만 내자~<br>미군 나가면 주식 반토막은 정해진 사실이다~",
      "contentSwReplacedButImg": "난 군대 갔다왔으니까 꼭하자~~ 북한처럼 남자 10년 여자들 7년씩 군대 생활 하고 싶다는데 ~~ 꼭해라~~ 자주국방타령하니까 IRI에서 장동혁대표 초청한걸 가지고 무식한넘들이 놀러갔다고 선동하니까 그 선동질에 놀아나는꼴이라니 ㅋㅋㅋ 자주국방해서 주식 반토만 내자~ 미군 나가면 주식 반토막은 정해진 사실이다~",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 85, \"st\": 99}, \"dis\": \"N\"}]}, \"id\": \"01KPF1KR95HRQ34PK2PECAZQ7M\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-3519e6ca-7af5-4758-b3b3-ca959300ea2b\", \"value\": [{\"id\": \"SE-34785911-ef39-40be-a749-5f8a428cd7af\", \"nodes\": [{\"id\": \"SE-148c2230-b8a2-41be-be6a-0a07bf9d40ae\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"난 군대 갔다왔으니까 꼭하자~~\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-289d1079-36ec-46a2-b8b8-d0b262d52cdf\", \"nodes\": [{\"id\": \"SE-79b19301-4f09-4824-9d02-7ac223e216af\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-2ef34050-d120-42f2-8dc3-fb2c44760e43\", \"nodes\": [{\"id\": \"SE-a65375b9-3a83-421c-a601-f079d6cfdcb8\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"북한처럼 남자 10년 여자들 7년씩 군대 생활 하고 싶다는데 ~~\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-7a05c2a9-4ba8-4644-8ca4-3f1de1f981a3\", \"nodes\": [{\"id\": \"SE-b063b24a-f835-4743-a835-0158622426fd\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"꼭해라~~\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-7e6879ec-f582-47a5-b045-e33c4f127a88\", \"nodes\": [{\"id\": \"SE-1f9a2f70-4064-41e1-8e53-f06c2c3552df\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-5334d1da-b121-4952-8a15-29231d8fb816\", \"nodes\": [{\"id\": \"SE-8210e972-7e85-4d95-8bdb-4fdcd2b8bd03\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"자주국방타령하니까 IRI에서 장동혁대표 초청한걸 가지고\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-724138a4-8998-4f86-bd40-7bfa7875b4de\", \"nodes\": [{\"id\": \"SE-d6948fb3-183e-47d2-aa13-6c73590260ab\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-6ab4e725-2d98-4e8a-b306-a45b8dc348e3\", \"nodes\": [{\"id\": \"SE-16bde12a-8159-4356-98ae-b7edb1b37f22\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"무식한넘들이 놀러갔다고 선동하니까 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-1e4d2b62-9c3e-47b6-ab95-357295c77003\", \"nodes\": [{\"id\": \"SE-480727c8-8b7c-494a-b120-67444d5ac042\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"그 선동질에 놀아나는꼴이라니 ㅋㅋㅋ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-f42ebf70-d6a0-4189-85be-44195ef28fa0\", \"nodes\": [{\"id\": \"SE-681e599b-ecea-4cdb-b053-0fff0e27fcc8\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-63d35bc1-e59b-4e31-b3cf-f5cbe784b6af\", \"nodes\": [{\"id\": \"SE-0f20e040-89f6-4f38-975e-56ff50155346\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"자주국방해서 주식 반토만 내자~\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-083ca624-ebb3-43fd-bd27-0f0d9082589f\", \"nodes\": [{\"id\": \"SE-56c19dfa-bb07-44e4-a239-d783a5a6324e\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"미군 나가면 주식 반토막은 정해진 사실이다~\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417878610",
      "orderNo": "-417878610",
      "discussionType": "domesticStock",
      "itemCode": "005930",
      "itemName": "삼성전자",
      "postType": "normal",
      "writer": {
        "profileId": "28660210597813865",
        "profileType": "normal",
        "nickname": "Dragon",
        "imageUrl": "https://ssl.pstatic.net/imgstock/fn/real/_front/image/profile/bonnie.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T10:01:26",
      "title": "마이크론 샌디스크 하락",
      "contentSwReplaced": "고로 삼전 하락",
      "contentSwReplacedButImg": "고로 삼전 하락",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 11, \"st\": 24}, \"dis\": \"N\"}]}, \"id\": \"01KPF1NYJE6T0RRTTWQJRVJXHM\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-e057fae7-c50c-427b-aa26-99fae942bec1\", \"value\": [{\"id\": \"SE-b9999775-dc78-4254-aa51-884749545eff\", \"nodes\": [{\"id\": \"SE-abf543c8-0ff1-45ec-93b2-1ae302601ea6\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"고로 삼전 하락\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417878604",
      "orderNo": "-417878604",
      "discussionType": "domesticStock",
      "itemCode": "005930",
      "itemName": "삼성전자",
      "postType": "normal",
      "writer": {
        "profileId": "28659778623397222",
        "profileType": "normal",
        "nickname": "시장과자유",
        "imageUrl": null,
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T10:01:17",
      "title": "항소포기하라고 지침준 사람이 없다는데",
      "contentSwReplaced": "항소포기가 되어 있음. 유령이 지시 했나?",
      "contentSwReplacedButImg": "항소포기가 되어 있음. 유령이 지시 했나?",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 36, \"st\": 73}, \"dis\": \"N\"}]}, \"id\": \"01KPF1M6RTBDE5TH7C0730N7N9\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-e4d56463-44ed-4cef-95d9-4a62443df8d0\", \"value\": [{\"id\": \"SE-1fda6cdb-32a0-44e7-8f06-2d9129ba5c96\", \"nodes\": [{\"id\": \"SE-0681634f-ac2e-4252-a6e3-6b8d6eec1943\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"항소포기가 되어 있음. 유령이 지시 했나?\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417878582",
      "orderNo": "-417878582",
      "discussionType": "domesticStock",
      "itemCode": "005930",
      "itemName": "삼성전자",
      "postType": "normal",
      "writer": {
        "profileId": "28658691377157784",
        "profileType": "normal",
        "nickname": "메흐메트2세",
        "imageUrl": "https://sec-discuss-phinf.pstatic.net/MjAyNTA3MDJfMTM2/MDAxNzUxNDUxNTcyMjE2.-PLDKQ4A-WpRPWxvBH5wBIahs_9OUM1oGaaKnQgh07Yg.YAGdScjyd4rZHbJdQepq8kx7PhPXAYRNmfJA2D971Zwg.PNG/profile_20250702191932.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T10:00:12",
      "title": "상법개정과 초양극화",
      "contentSwReplaced": "지금 상법개정 이런 게 나오는 거는 본질이<br>기업 위주에서 자본 위주로 바뀌고 있다는 거다<br>사실 우리나라는 제도로 강제하면서 빠르게<br>진행되고 있다 그래서 이게 전광석화처럼<br>기업에서 자본위주로 움직이고 있는 거다<br>이렇게 되면 주주 즉 자본가는 좋지 왜냐하면<br>이게 상법개정 본질은 바로 니들 돈 쟁여놨지?<br>근데 왜 배당 안줘? 주식 소각 안해? 주주가치를<br>높이는 행동을 안하는 거야? 이런 거다<br>즉 간단하게 회사에 쌓인 돈 다 내놔 이거다<br>성장의 시대에는 기업에게 재량을 주고 기업을<br>우선으로 했지만 이제 저성장시대 기업에<br>쌓인 돈 다 내놔 이렇게 되고 있는 거다<br>이런 식으로 가면 초양극화가 일어날 수밖에 없다<br>자본이 기업을 지배하게 되기 때문이지<br>지금 미국 이란 전쟁 등 원유 수급 불안정성<br>고유가 고물가 고금리로 이어질 거고 환율도<br>높게 유지되겠지 이것도 초양극화를 자극할 거고<br>우리나라 이제 성장의 시대는 저물었고 그<br>신호탄이 상법개정이다 그렇기 때문에 이번<br>코스피 2000에서 6000 갔는데 이 때 돈 못 번<br>사람들은 앞으로 기회가 영영 없을 수도 있다<br>물론 더 오를 수도 있는데 아무튼 얼마 안 남았다<br>이 시기 놓치면 이제 부자되기 진짜 어려워 질 거다<br>결론은 상법개정, 전쟁으로 인한 고유가 국내외적으로<br>초양극화를 자극할 수 있는 것만 일어나고 있다 이거다",
      "contentSwReplacedButImg": "지금 상법개정 이런 게 나오는 거는 본질이 기업 위주에서 자본 위주로 바뀌고 있다는 거다 사실 우리나라는 제도로 강제하면서 빠르게 진행되고 있다 그래서 이게 전광석화처럼 기업에서 자본위주로 움직이고 있는 거다 이렇게 되면 주주 즉 자본가는 좋지 왜냐하면 이게 상법개정 본질은 바로 니들 돈 쟁여놨지? 근데 왜 배당 안줘? 주식 소각 안해? 주주가치를 높이는 행동을 안하는 거야? 이런 거다 즉 간단하게 회사에 쌓인 돈 다 내놔 이거다 성장의 시대에는 기업에게 재량을 주고 기업을 우선으로 했지만 이제 저성장시대 기업에 쌓인 돈 다 내놔 이렇게 되고 있는 거다 이런 식으로 가면 초양극화가 일어날 수밖에 없다 자본이 기업을 지배하게 되기 때문이지 지금 미국 이란 전쟁 등 원유 수급 불안정성 고유가 고물가 고금리로 이어질 거고 환율도 높게 유지되겠지 이것도 초양극화를 자극할 거고 우리나라 이제 성장의 시대는 저물었고 그 신호탄이 상법개정이다 그렇기 때문에 이번 코스피 2000에서 6000 갔는데 이 때 돈 못 번 사람들은 앞으로 기회가 영영 없을 수도 있다 물론 더 오를 수도 있는데 아무튼 얼마 안 남았다 이 시기 놓치면 이제 부자되기 진짜 어려워 질 거다 결론은 상법개정, 전쟁으로 인한 고유가 국내외적으로 초양극화를 자극할 수 있는 것만 일어나고 있다 이거다",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 355, \"st\": 429}, \"dis\": \"N\"}]}, \"id\": \"01KPF17MTHG9AWMYS0W9N48WK3\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-3aec2ad0-4212-43bd-89fd-d71a76d0f6c7\", \"value\": [{\"id\": \"SE-b2e1759d-d755-43b0-ad27-1e13d56f47fe\", \"nodes\": [{\"id\": \"SE-a266ef20-4702-4135-9840-0440df220f9e\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"지금 상법개정 이런 게 나오는 거는 본질이\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-0c54f340-3c45-492b-8f4c-6d6b64f12719\", \"nodes\": [{\"id\": \"SE-48119dde-3afe-468f-b251-c54d6c7713c7\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"기업 위주에서 자본 위주로 바뀌고 있다는 거다\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-f1be6eff-3faa-4e65-a087-e6f0080ae05c\", \"nodes\": [{\"id\": \"SE-7b544278-297e-47ed-b6be-3142469cbe96\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"사실 우리나라는 제도로 강제하면서 빠르게 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-aa417ed5-203f-43a8-80bd-9226b6373580\", \"nodes\": [{\"id\": \"SE-d871a38a-0ee0-4aed-887a-64a47bba562e\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"진행되고 있다 그래서 이게 전광석화처럼\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-e1cb3cbc-da6d-4363-a2df-c54016fa774b\", \"nodes\": [{\"id\": \"SE-9987283e-32d7-4576-97e2-d3fde9d6373f\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"기업에서 자본위주로 움직이고 있는 거다 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-63ed5127-8306-4db5-9bee-cb2339eae480\", \"nodes\": [{\"id\": \"SE-cac566a4-b7f4-4361-b7a8-6342fcf76567\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"이렇게 되면 주주 즉 자본가는 좋지 왜냐하면\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-5766682f-a1cd-477c-b336-7dc4e79f00f6\", \"nodes\": [{\"id\": \"SE-a6cc6418-a824-4833-9c4a-df746ba8d98f\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"이게 상법개정 본질은 바로 니들 돈 쟁여놨지?\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-a7fc3e59-463d-45df-ad47-fb4ccee4121c\", \"nodes\": [{\"id\": \"SE-00ca103f-0724-4095-8709-7d8b1a095f22\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"근데 왜 배당 안줘? 주식 소각 안해? 주주가치를\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-8a304e88-53df-46dd-b8c7-0edf3c3ed712\", \"nodes\": [{\"id\": \"SE-01caa901-b405-44e8-b420-4edbab0942ba\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"높이는 행동을 안하는 거야? 이런 거다 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-55884d7c-744e-4fd3-85cf-a830b90397e1\", \"nodes\": [{\"id\": \"SE-96b59f89-c942-4f45-adbf-f3b2ac1552a6\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"즉 간단하게 회사에 쌓인 돈 다 내놔 이거다\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-145219f8-e749-4cbc-8202-fb3668401661\", \"nodes\": [{\"id\": \"SE-abb41e7e-2f22-46b8-8b2e-b048c97e5c8c\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"성장의 시대에는 기업에게 재량을 주고 기업을 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-9f1c1373-ceb8-49c6-9cad-02e97c6e2c58\", \"nodes\": [{\"id\": \"SE-cfdfa3eb-1c6e-4055-a607-3212751b2440\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"우선으로 했지만 이제 저성장시대 기업에\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-a2522137-e3a4-492c-a5ae-2259c439d032\", \"nodes\": [{\"id\": \"SE-50fb4279-0764-4517-b8e2-23c515f19a3c\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"쌓인 돈 다 내놔 이렇게 되고 있는 거다 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-8234444e-2491-43e1-9c60-d7f8a4c60047\", \"nodes\": [{\"id\": \"SE-2032f3b4-39ce-40e9-984a-96c73e4377cd\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"이런 식으로 가면 초양극화가 일어날 수밖에 없다 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-eb1b319d-817d-48ad-b1de-70acd8a1e12b\", \"nodes\": [{\"id\": \"SE-78391b73-84cb-443a-b771-957cd7d391fa\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"자본이 기업을 지배하게 되기 때문이지 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-7a2f2fca-1d34-4d1a-a0cc-ebd8353ebcb9\", \"nodes\": [{\"id\": \"SE-914a8b2c-93c4-4d85-a0e2-914c75c7eb64\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"지금 미국 이란 전쟁 등 원유 수급 불안정성\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-70d498a1-9f5c-404d-9eae-33eecc3bbe83\", \"nodes\": [{\"id\": \"SE-d1ed5eea-3f7b-404e-8045-3b2a5adf0645\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"고유가 고물가 고금리로 이어질 거고 환율도\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-f6a39f75-ac53-43ca-948a-50b410686577\", \"nodes\": [{\"id\": \"SE-cb0f3db6-7f93-4c43-846a-9f0f9006f6c8\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"높게 유지되겠지 이것도 초양극화를 자극할 거고\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-b51b8521-18d0-4bfa-b598-3750895d6d3f\", \"nodes\": [{\"id\": \"SE-84934696-7b64-476f-a3e6-a1c32272282d\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"우리나라 이제 성장의 시대는 저물었고 그 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-9b2d0f5a-f1a3-46bc-b462-28d2eae4a6f5\", \"nodes\": [{\"id\": \"SE-95f09db9-bd00-45a5-bd26-70af12846c3f\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"신호탄이 상법개정이다 그렇기 때문에 이번 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-57d3c0df-3bc2-4ce2-901e-412644e50a7d\", \"nodes\": [{\"id\": \"SE-cab0d722-f090-4e5b-946e-155cc48b3439\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"코스피 2000에서 6000 갔는데 이 때 돈 못 번 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-15bd1ca8-e410-42c0-9020-819ef9fc28c1\", \"nodes\": [{\"id\": \"SE-5f79dee6-6c7e-4c6d-a147-8c7b91784dba\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"사람들은 앞으로 기회가 영영 없을 수도 있다\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-42fb9322-db2f-4a0f-a98e-aa527d4dded0\", \"nodes\": [{\"id\": \"SE-2eebfee5-d196-4804-8763-775990e7b646\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"물론 더 오를 수도 있는데 아무튼 얼마 안 남았다 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-e1a9f02a-1d99-4e75-b772-17f572e5c4a0\", \"nodes\": [{\"id\": \"SE-7cd5adb4-9868-4a0a-a62b-b2fd000d60bc\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"이 시기 놓치면 이제 부자되기 진짜 어려워 질 거다\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-7dc119c1-1e87-4a06-805d-418e277dafb9\", \"nodes\": [{\"id\": \"SE-9705368a-0d40-4eeb-9c16-6220831c05fe\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"결론은 상법개정, 전쟁으로 인한 고유가 국내외적으로\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-97c802a3-eed6-4395-bc63-3652fd85608d\", \"nodes\": [{\"id\": \"SE-d61c98c6-cdd1-4936-b756-69dcc84a5db9\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"초양극화를 자극할 수 있는 것만 일어나고 있다 이거다\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-64447e40-fe66-483b-b9eb-7d3471365940\", \"nodes\": [{\"id\": \"SE-7bd18b56-839a-49a1-9123-1ea423fd9b0c\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    }
  ],
  "lastOffset": "-417878213"
} as const;

export const NAVER_BOARD_JSON_SAMPLE_QUIET: NaverDiscussionApiResponse = {
  "offset": "-9223372036854775807",
  "pageSize": 50,
  "posts": [
    {
      "id": "417877327",
      "orderNo": "-417877327",
      "discussionType": "domesticStock",
      "itemCode": "247540",
      "itemName": "에코프로비엠",
      "postType": "normal",
      "writer": {
        "profileId": "28660113468984971",
        "profileType": "normal",
        "nickname": "슈팅고고",
        "imageUrl": null,
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T08:52:46",
      "title": "아픈 손가락들",
      "contentSwReplaced": "퓨처엠과 더블어 아픈 손가락 비엠<br>바닥인줄 아는데도 질려서 매수도<br>하기 싫게 만들었던 2차전지 주역들<br>옛날의 영광이 다시 돌아 올거라고 믿고 기다렸는데 금양 죽은걸보며  주식 수업료를 크게 치뤘네요",
      "contentSwReplacedButImg": "퓨처엠과 더블어 아픈 손가락 비엠 바닥인줄 아는데도 질려서 매수도 하기 싫게 만들었던 2차전지 주역들 옛날의 영광이 다시 돌아 올거라고 믿고 기다렸는데 금양 죽은걸보며 주식 수업료를 크게 치뤘네요",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 489, \"st\": 636}, \"dis\": \"N\"}]}, \"id\": \"01KPEX5HCDCQYABNABWN2WW7KW\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-458c6688-4b25-4545-b605-f3e59a5c22a3\", \"value\": [{\"id\": \"SE-076d283b-e862-4867-ad18-f4522bab90d8\", \"nodes\": [{\"id\": \"SE-02199aad-4710-46f0-a5dd-e582f5f30222\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"퓨처엠과 더블어 아픈 손가락 비엠\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-f632d2d8-be84-4f83-b147-9b19f6aa2778\", \"nodes\": [{\"id\": \"SE-fc02c284-5f9a-4fa8-af4a-0fdbdc291049\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"바닥인줄 아는데도 질려서 매수도\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-45d123db-8959-463f-8878-08e149d62fca\", \"nodes\": [{\"id\": \"SE-a9fad270-6c22-4057-a11d-87aa9e376539\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"하기 싫게 만들었던 2차전지 주역들\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-d2e19352-dd99-4f22-8327-c965e7063f87\", \"nodes\": [{\"id\": \"SE-a33abffb-dad1-4afb-965b-8f79913870ae\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"옛날의 영광이 다시 돌아 올거라고 믿고 기다렸는데 금양 죽은걸보며  주식 수업료를 크게 치뤘네요\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-44977338-5ec9-45f3-b7b3-9c809320a724\", \"nodes\": [{\"id\": \"SE-d0524c0e-a4a5-40b2-9a1d-a881656ea7ed\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417877092",
      "orderNo": "-417877092",
      "discussionType": "domesticStock",
      "itemCode": "247540",
      "itemName": "에코프로비엠",
      "postType": "normal",
      "writer": {
        "profileId": "28660366370001073",
        "profileType": "normal",
        "nickname": "GtF",
        "imageUrl": "https://ssl.pstatic.net/imgstock/fn/real/_front/image/profile/avatar-10.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T08:39:32",
      "title": "유럽판 IRA, 삼성SDI 44조 수주, 헝가리 공장 본격적 상업생산 걔시!.",
      "contentSwReplaced": "헝가리 공장 시설투자 완료되었고 올해 상반기내에 본격적인 상업 생산 시작. 삼성sdi와 44조 수주 계약 본격적으로 소진 확실시됨. 유럽판 IRA",
      "contentSwReplacedButImg": "헝가리 공장 시설투자 완료되었고 올해 상반기내에 본격적인 상업 생산 시작. 삼성sdi와 44조 수주 계약 본격적으로 소진 확실시됨. 유럽판 IRA",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 0, \"st\": 59}, \"dis\": \"N\"}]}, \"id\": \"01KPEWYXW054PYGS1P5NSX6YM6\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-bf6dc2fe-c8e0-440e-9359-a9eef3c2ae5d\", \"value\": [{\"id\": \"SE-1e03224a-dad0-4fd5-b713-27b5218f82dc\", \"nodes\": [{\"id\": \"SE-9f8ad4e0-d73f-4770-873f-52853859e74a\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"헝가리 공장 시설투자 완료되었고 올해 상반기내에 본격적인 상업 생산 시작. 삼성sdi와 44조 수주 계약 본격적으로 소진 확실시됨. 유럽판 IRA\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417875975",
      "orderNo": "-417875975",
      "discussionType": "domesticStock",
      "itemCode": "247540",
      "itemName": "에코프로비엠",
      "postType": "normal",
      "writer": {
        "profileId": "28660333013101512",
        "profileType": "normal",
        "nickname": "LiOH",
        "imageUrl": "https://ssl.pstatic.net/imgstock/fn/real/_front/image/profile/avatar-9.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T07:35:00",
      "title": "에코프로는 왜 힘이없냐고",
      "contentSwReplaced": "경쟁업체대비 안오른다, 힘이없다, 시세를 안준다<br>이런얘기가 많은데 시가총액 볼줄 몰라요?<br>에코프로 20조 에코프로비엠 20조 = 40조 +<br>연매출 40~50조 하는 LG화학 25조인데..<br>(엘앤에프 고작 7.5조;;;;)<br>이미 엄청 많이 오른거아닌가..?;;;;<br>양심이 없어도 너무 없네..ㄷㄷ",
      "contentSwReplacedButImg": "경쟁업체대비 안오른다, 힘이없다, 시세를 안준다 이런얘기가 많은데 시가총액 볼줄 몰라요? 에코프로 20조 에코프로비엠 20조 = 40조 + 연매출 40~50조 하는 LG화학 25조인데.. (엘앤에프 고작 7.5조;;;;) 이미 엄청 많이 오른거아닌가..?;;;; 양심이 없어도 너무 없네..ㄷㄷ",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 198, \"st\": 246}, \"dis\": \"N\"}]}, \"id\": \"01KPES4XFEXC95HAC7F63D8M7W\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-5253b494-9f6b-4235-a5dc-224f9f408ad1\", \"value\": [{\"id\": \"SE-84d49710-b037-4bc3-a114-ecbcae6b52af\", \"nodes\": [{\"id\": \"SE-d101749e-d3aa-45ac-be01-de33187f1c8c\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"경쟁업체대비 안오른다, 힘이없다, 시세를 안준다 \", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-63273b5c-8baa-44dd-9303-c718f93cf11a\", \"nodes\": [{\"id\": \"SE-67aee691-90ce-4ef2-adac-207b187ad85e\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"이런얘기가 많은데 시가총액 볼줄 몰라요?\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-990fe6bd-1115-49d7-b734-38bcc57db9c6\", \"nodes\": [{\"id\": \"SE-4df63ea1-8127-4be1-be93-e11c827bcc83\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"에코프로 20조 에코프로비엠 20조 = 40조 +\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-e8ca40d8-9d18-4d33-a6cb-8fdb615dc87a\", \"nodes\": [{\"id\": \"SE-3fc8f695-d264-4dee-82e3-6118d9bf933a\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"연매출 40~50조 하는 LG화학 25조인데..\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-e93b41c8-ba2a-47e4-9c01-fa44aa88e559\", \"nodes\": [{\"id\": \"SE-b8b4b472-964b-4db1-b619-cacdd1613a6e\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"(엘앤에프 고작 7.5조;;;;)\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-880a2d78-1834-428d-a652-31ea46b73cf8\", \"nodes\": [{\"id\": \"SE-45e93ce4-e170-4bc4-b7eb-355997ccb155\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"이미 엄청 많이 오른거아닌가..?;;;;\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-734aa07a-097a-461a-a3ff-394d3bed4eda\", \"nodes\": [{\"id\": \"SE-306ddb68-37b2-4864-9c38-3764b94e72b4\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"양심이 없어도 너무 없네..ㄷㄷ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417875706",
      "orderNo": "-417875706",
      "discussionType": "domesticStock",
      "itemCode": "247540",
      "itemName": "에코프로비엠",
      "postType": "normal",
      "writer": {
        "profileId": "28660113721401002",
        "profileType": "normal",
        "nickname": "ㅍㅂㄹdQㅃㄺㅅ",
        "imageUrl": "https://ssl.pstatic.net/imgstock/fn/real/_front/image/profile/avatar-9.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T07:11:41",
      "title": "조그만한 불법 보이면 재명이한테 꼬질러.",
      "contentSwReplaced": "재명이<br>질리도록 꼬질러라.<br>계좌 지킬려면 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ<br><img class=\"se-preview-sticker\" src=\"https://storep-phinf.pstatic.net/paypet_01/original_3.gif?type=pa100_100\"/>",
      "contentSwReplacedButImg": "재명이 질리도록 꼬질러라. 계좌 지킬려면 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 17, \"st\": 39}, \"dis\": \"N\"}]}, \"id\": \"01KPEQYNNS00057V8AZNMNHTD7\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-98380740-852a-4be2-a9d2-1155c6a13867\", \"value\": [{\"id\": \"SE-98a22ed7-0c46-4f0e-8174-58a6b4342359\", \"nodes\": [{\"id\": \"SE-6aaa6d8f-cf67-4f63-8c24-7dd7570eb94f\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"재명이\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-4426ca71-4aff-4a9c-a02f-dd30a48199a6\", \"nodes\": [{\"id\": \"SE-77291cc4-0d1d-4603-9e89-3baaca0cdd31\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"질리도록 꼬질러라.\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-40eec85e-e96c-4d48-8419-57fe6c9a5c7e\", \"nodes\": [{\"id\": \"SE-ce269d2c-4c03-4020-867c-dbdf331ba541\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-4c0aa032-11af-47bb-823c-230f23073886\", \"nodes\": [{\"id\": \"SE-6e7d78c6-9140-4969-b303-35443c6d2123\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"계좌 지킬려면 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-83db0e0f-a7a3-49e8-ba0e-86fce7fc61fa\", \"nodes\": [{\"id\": \"SE-e77fa315-4b8c-45c8-8b5c-063716f512d1\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}, {\"id\": \"SE-c3c0a81f-46e4-4925-9f7b-cff649ea2ef9\", \"seq\": 3, \"@ctype\": \"sticker\", \"format\": \"animated\", \"layout\": \"default\", \"packCode\": \"paypet_01\", \"thumbnail\": {\"src\": \"https://storep-phinf.pstatic.net/paypet_01/original_3.gif\", \"width\": 185, \"@ctype\": \"thumbnail\", \"height\": 160}}, {\"id\": \"SE-38bbb2f9-01ee-4ae2-ba07-390c91f1a9e8\", \"value\": [{\"id\": \"SE-7b08a961-6574-411c-846b-724b955b5aae\", \"nodes\": [{\"id\": \"SE-a43d4481-619c-4ecf-a030-3de1f3479eb9\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    },
    {
      "id": "417875687",
      "orderNo": "-417875687",
      "discussionType": "domesticStock",
      "itemCode": "247540",
      "itemName": "에코프로비엠",
      "postType": "normal",
      "writer": {
        "profileId": "28660113721401002",
        "profileType": "normal",
        "nickname": "ㅍㅂㄹdQㅃㄺㅅ",
        "imageUrl": "https://ssl.pstatic.net/imgstock/fn/real/_front/image/profile/avatar-9.png",
        "isHolderVerified": false,
        "isNiConnected": false,
        "isRequester": false,
        "isFollowed": false,
        "notFollowed": false
      },
      "writtenAt": "2026-04-18T07:09:42",
      "title": "올 재떨뤼 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ",
      "contentSwReplaced": "주말 특근 나왔능가 ㅋ<br>울<br>떨뤼 뿐이고 ㅋㅋ<br>열심히 혀라.<br>월요일날 빳빳하게 함 세워보자잉 ㅋㅋㅋㅋㅋ<br><img class=\"se-preview-sticker\" src=\"https://storep-phinf.pstatic.net/paypet_01/original_3.gif?type=pa100_100\"/>",
      "contentSwReplacedButImg": "주말 특근 나왔능가 ㅋ 울 떨뤼 뿐이고 ㅋㅋ 열심히 혀라. 월요일날 빳빳하게 함 세워보자잉 ㅋㅋㅋㅋㅋ",
      "contentJsonSwReplaced": "{\"document\": {\"di\": {\"dif\": false, \"dio\": [{\"dia\": {\"p\": 0, \"t\": 0, \"sk\": 33, \"st\": 49}, \"dis\": \"N\"}]}, \"id\": \"01KPEQTR593CPMA20DD47B228Q\", \"theme\": \"default\", \"version\": \"2.9.0\", \"language\": \"ko-KR\", \"components\": [{\"id\": \"SE-f8615581-b07b-475e-83c6-4c5a28cc1f69\", \"value\": [{\"id\": \"SE-ea86cfcd-ee84-4ef7-83e1-43b739cf16ff\", \"nodes\": [{\"id\": \"SE-7c6c0a2f-e680-410d-8e3c-6a767e77d63b\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"주말 특근 나왔능가 ㅋ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-959e2626-0173-4695-87de-a0d1cfef4819\", \"nodes\": [{\"id\": \"SE-87fc8822-e082-4c8e-9496-b7278b6659bf\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"울\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-42d5665e-4e9a-4414-aa68-2d92656ae1fa\", \"nodes\": [{\"id\": \"SE-5b3f5b1a-9cc1-4c20-a98a-6505129a51bc\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"떨뤼 뿐이고 ㅋㅋ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-a1eb77e0-bed2-431f-bc72-3f51fedf1028\", \"nodes\": [{\"id\": \"SE-6046fd69-7b32-4dfd-9e53-7dd6ed507ec9\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-d0820269-e2d1-4e6b-88f6-c02af7a5b01f\", \"nodes\": [{\"id\": \"SE-bfd50cfd-d7ad-4ca3-b717-b3cce86dc629\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"열심히 혀라.\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-808ad13d-0052-417a-af65-cc27b38a36fd\", \"nodes\": [{\"id\": \"SE-8f9ee213-c627-411e-a315-2747fc5ccdd1\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"월요일날 빳빳하게 함 세워보자잉 ㅋㅋㅋㅋㅋ\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}, {\"id\": \"SE-d2c4512f-8a80-4dba-bdc2-12f3dd7c2c91\", \"nodes\": [{\"id\": \"SE-7a21156d-1de1-4619-874c-e1f275059b75\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}, {\"id\": \"SE-d5c573cf-d573-464c-beec-5ca2d7e8c6bd\", \"seq\": 3, \"@ctype\": \"sticker\", \"format\": \"animated\", \"layout\": \"default\", \"packCode\": \"paypet_01\", \"thumbnail\": {\"src\": \"https://storep-phinf.pstatic.net/paypet_01/original_3.gif\", \"width\": 185, \"@ctype\": \"thumbnail\", \"height\": 160}}, {\"id\": \"SE-57192ff7-17d9-4766-a85f-4b55712b5962\", \"value\": [{\"id\": \"SE-7d547066-5318-4e2e-8c81-2c6187f6c6b4\", \"nodes\": [{\"id\": \"SE-bbe8ae6b-e767-4320-94b9-e00867c80dd5\", \"style\": {\"@ctype\": \"nodeStyle\", \"fontColor\": \"#1E1E23\", \"fontFamily\": \"system\"}, \"value\": \"\", \"@ctype\": \"textNode\"}], \"style\": {\"@ctype\": \"paragraphStyle\", \"lineHeight\": 1.5}, \"@ctype\": \"paragraph\"}], \"@ctype\": \"text\", \"layout\": \"default\"}]}, \"documentId\": \"\"}",
      "topImageUrl": null,
      "topImageType": "NONE",
      "imageCount": 0,
      "isHolderVerified": false,
      "isCleanbotPassed": true,
      "replyDepth": 0,
      "parentId": null,
      "childOrderNo": 0,
      "commentCount": 0,
      "recommended": false,
      "notRecommended": false,
      "reactionId": null,
      "recommendCount": 0,
      "notRecommendCount": 0
    }
  ],
  "lastOffset": "-417848072"
} as const;
